version = 1

# Python analyzer
[[analyzers]]
name = "python"
enabled = true
  [analyzers.meta]
  runtime_version = "3.11"            # match your Python version
  paths = ["api"]                     # scan all Python files in api folder
  exclude = []                         # include everything

# JavaScript analyzer
[[analyzers]]
name = "javascript"
enabled = true
  [analyzers.meta]
  runtime_version = "18"              # Node.js version
  paths = ["api/static/js", "api/package.json"]

# HTML analyzer
[[analyzers]]
name = "html"
enabled = true
  [analyzers.meta]
  paths = ["api/templates"]

# CSS analyzer
[[analyzers]]
name = "css"
enabled = true
  [analyzers.meta]
  paths = ["api/static/css"]

# Disable autofix
[[autofixers]]
name = "python"
enabled = false

[[autofixers]]
name = "javascript"
enabled = false

[[autofixers]]
name = "html"
enabled = false

[[autofixers]]
name = "css"
enabled = false
